### ISSUE TITLE
Make the GUI window pop up in front of the viewer

### ISSUE THREAD

**Issue by goatchurchprime** [aaronfranke/godot-GUI-in-VR#1]
The UI panel comes up at position (0,0) at the centre of the playing area, which is behind me when I am working at my desk, and was invisible because it's back-culled.  

When in use in a game, the GUI will probably want to pop up in front of the player on a button press.

My *not-very-good* code for doing this was hacked in like this:

```GDScript
# in Player.gd
const VR_BUTTON_BY = 1
func _on_button_pressed(p_button):
	if p_button == VR_BUTTON_BY:
		var pos = $RightController.global_transform.origin - 0.8*_ws*($RightController.global_transform.basis.z)
		var trans = Transform($RightController.global_transform)
		trans = trans.scaled(Vector3(2, 2, 2))
		trans.origin = pos
		get_node("../GUIPanel3D").global_transform = trans

# In _ready()
	$RightController.connect("button_pressed", self, "_on_button_pressed")
```

Or one can use the `looking_at()` function with a point behind the panel to create it the right way up.  The 2x scale applied to the GUIPanel3D is a nuisance because it keeps getting lost by these transform functions.

```GDScript
		var paneltrans = get_node("../GUIPanel3D").global_transform
		var controllertrans = $RightController.global_transform
		paneltrans.origin = controllertrans.origin - 0.8*_ws*(controllertrans.basis.z)
		var lookatpos = controllertrans.origin - 1.6*_ws*(controllertrans.basis.z)
		paneltrans = paneltrans.looking_at(lookatpos, Vector3(0, 1, 0))
		get_node("../GUIPanel3D").global_transform = paneltrans
```

**Comment by aaronfranke** [comment]
I appreciate the feedback, but this demo is supposed to be simple and these changes would add complexity which is not really necessary for the purposes of this demo. Therefore I'm closing this.

The scale isn't so bad, it helps test that the script works for scaled objects.
