### ISSUE TITLE
GUI panel not visibly editable in 2D mode

### ISSUE THREAD

**Issue by goatchurchprime** [aaronfranke/godot-GUI-in-VR#3]
If I am in the GUIPanel3D scene and select the Viewport/GUI all I have is a blank grey window.  Each of the nodes (Label, Button, etc) can be selected and inspected in the Treeview, but there is no 2D preview at all.  

If I right-click on the GUI node and "Save Branch as Scene", then all the components are editable in the 2D view of this new scene.  

What is the recommended method for editing the GUI?

It's also very difficult to recreate the demo without simply importing it completely, because it's not obvious what all the settings need to be.  It seems that the material on the mesh needs to be empty, but material/0 needs to be set to a Viewport texture.  

Initially when you try to set it, it gives an error:  'Can't create a viewport texture on this resource because it's not set as local to scene. please switch on the "local to scene" property on it (and all resources containing it up to a node)' 

This sends you to the wrong place.  It needs to be the "Local to scene" setting on the spacial material, not the "Local to scene" setting on the MeshInstance, as described in [this help](https://godotengine.org/qa/40907/help-with-the-godot-docs-tutorial-using-viewport-as-texture)

These duplicate settings (material and material, or local and local) makes it very difficult to follow instructions, because you believe you have followed them to the letter when you have not!

**Comment by aaronfranke** [comment]
The GUI not showing up in the 2D editor is a limitation of Godot and I think the only workaround is to save the GUI as a separate scene. I wasn't worried about it for this project since I just copied the GUI from the GUI in 3D demo, but yeah it would be nice. I just pushed a commit moving it to its own scene.

**Comment by goatchurchprime** [comment]
I cannot see why, just because it's a subnode of a Viewport, it won't show anything.  

I was sure you were going to tell me a secret setting in the Viewport node that fixes it.  But it still happens in the main demo examples:  https://github.com/godotengine/godot-demo-projects/tree/master/viewport/gui_in_3d

Here's another crazy work-around: When you want work on the GUI, temporarily drag it out from the Viewport to anywhere else in the tree, do your editing, and then drag it back in.  

I've looked in the main godotengine issues and can't find this one listed anywhere.

**Comment by goatchurchprime** [comment]
I've reproduced and reported this issue https://github.com/godotengine/godot/issues/39387

**Comment by aaronfranke** [comment]
Sorry, I forgot to close this. The GUI is now a separate scene in the demo.
